import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateNewTables1774534313767 implements MigrationInterface {
    name = 'CreateNewTables1774534313767'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "categoria_insumo" ("id_categoria_insumo" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre_categoria" character varying(255) NOT NULL, CONSTRAINT "PK_a96716804a9cbfc656364d67a6e" PRIMARY KEY ("id_categoria_insumo"))`);
        await queryRunner.query(`CREATE TABLE "unidad_medida" ("id_unidad_medida" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" character varying(255) NOT NULL, "abreviatura" character varying(255) NOT NULL, CONSTRAINT "PK_dac609572f56f4807edf3dda2ad" PRIMARY KEY ("id_unidad_medida"))`);
        await queryRunner.query(`CREATE TABLE "accion_historial_movimiento" ("id_accion_historial_movimiento" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" character varying(255) NOT NULL, CONSTRAINT "PK_b80c01938238a33148b606f68fa" PRIMARY KEY ("id_accion_historial_movimiento"))`);
        await queryRunner.query(`CREATE TABLE "historial_insumo" ("id_historial_insumo" uuid NOT NULL DEFAULT uuid_generate_v4(), "id_insumos" uuid NOT NULL, "id_historial_accion" uuid NOT NULL, "cantidad" double precision NOT NULL, "descripcion" character varying(255) NOT NULL, "fecha" TIMESTAMP NOT NULL, CONSTRAINT "PK_ff7aa2f097292c1f972208a7f96" PRIMARY KEY ("id_historial_insumo"))`);
        await queryRunner.query(`CREATE TABLE "raza" ("id_raza" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" character varying(255) NOT NULL, "descripcion" character varying(255) NOT NULL, CONSTRAINT "PK_19cbb355eaf65fb4ca7544ff741" PRIMARY KEY ("id_raza"))`);
        await queryRunner.query(`CREATE TABLE "historial_asignacion_lote" ("id_historial_asignacion_lote" uuid NOT NULL DEFAULT uuid_generate_v4(), "cantidad_asignada" integer NOT NULL, "id_lote" uuid, "id_galpon" uuid, CONSTRAINT "PK_13c6f3f55a18d01f945125df158" PRIMARY KEY ("id_historial_asignacion_lote"))`);
        await queryRunner.query(`CREATE TABLE "galpon" ("id_galpon" uuid NOT NULL DEFAULT uuid_generate_v4(), "codigo" character varying NOT NULL, "nombre" character varying NOT NULL, "capacidad_max_aves" integer NOT NULL, "longitud" numeric NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_28bbda598d98e0f194c4bceb465" PRIMARY KEY ("id_galpon"))`);
        await queryRunner.query(`CREATE TABLE "ubicacion_lote" ("id_ubicacion_lote" uuid NOT NULL DEFAULT uuid_generate_v4(), "Fecha" TIMESTAMP NOT NULL DEFAULT now(), "id_lote" uuid, "id_galpon" uuid, CONSTRAINT "PK_955c40fe36a4b4e89fd237efe6e" PRIMARY KEY ("id_ubicacion_lote"))`);
        await queryRunner.query(`CREATE TABLE "estado_lote" ("id_estado_lote" uuid NOT NULL DEFAULT uuid_generate_v4(), "estado" character varying NOT NULL, "id_lote" uuid, CONSTRAINT "PK_fd47347ab9b2ffeabcc682eec9d" PRIMARY KEY ("id_estado_lote"))`);
        await queryRunner.query(`CREATE TABLE "huevo_dañado" ("id_huevo_dañado" uuid NOT NULL DEFAULT uuid_generate_v4(), "cantidad" integer NOT NULL, "razon" character varying NOT NULL, "registeredAt" TIMESTAMP NOT NULL DEFAULT now(), "inventarioIdInventarioHuevo" uuid, CONSTRAINT "PK_1e16c8c07593d065bf36d982581" PRIMARY KEY ("id_huevo_dañado"))`);
        await queryRunner.query(`CREATE TABLE "historial_huevo" ("id_historial_huevo" uuid NOT NULL DEFAULT uuid_generate_v4(), "usuarioId" character varying NOT NULL, "cantidad" integer NOT NULL, "fecha" TIMESTAMP NOT NULL DEFAULT now(), "inventarioIdInventarioHuevo" uuid, "produccionIdProduccionHuevo" uuid, CONSTRAINT "PK_8eded1d7b0ec9b4437c0bdb1442" PRIMARY KEY ("id_historial_huevo"))`);
        await queryRunner.query(`CREATE TABLE "tipo_huevo" ("id_tipo" uuid NOT NULL DEFAULT uuid_generate_v4(), "tipo" character varying(255) NOT NULL, "peso_min" numeric(10,2) NOT NULL, "peso_max" numeric(10,2) NOT NULL, CONSTRAINT "PK_b4271033b7fb583aa7fcfd3e59b" PRIMARY KEY ("id_tipo"))`);
        await queryRunner.query(`CREATE TABLE "inventario_huevo" ("id_inventario_huevo" uuid NOT NULL DEFAULT uuid_generate_v4(), "cantidad" integer NOT NULL, "tipo_huevo_id" uuid, "loteIdLote" uuid, "produccionIdProduccionHuevo" uuid, CONSTRAINT "PK_4f883b2ae2dccc24ee2e275f2d0" PRIMARY KEY ("id_inventario_huevo"))`);
        await queryRunner.query(`CREATE TABLE "produccion_huevo" ("id_produccion_huevo" uuid NOT NULL DEFAULT uuid_generate_v4(), "tipo_huevoId" character varying NOT NULL, "cantidady" integer NOT NULL, "produccionFecha" TIMESTAMP NOT NULL DEFAULT now(), "loteIdLote" uuid, CONSTRAINT "PK_aae60b7b9d35b29ba00c7e85554" PRIMARY KEY ("id_produccion_huevo"))`);
        await queryRunner.query(`CREATE TABLE "lote" ("id_lote" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" character varying NOT NULL, "total_aves" integer NOT NULL, "observacion" character varying NOT NULL, "racion_alimento" character varying NOT NULL, "estado" character varying NOT NULL, "id_raza" uuid, CONSTRAINT "PK_cd03609638866c3e8cb3dc2759b" PRIMARY KEY ("id_lote"))`);
        await queryRunner.query(`CREATE TABLE "alimentacion" ("id_alimentacion" uuid NOT NULL DEFAULT uuid_generate_v4(), "cantidad" numeric NOT NULL, "fecha" TIMESTAMP NOT NULL DEFAULT now(), "usuarioIdUsuario" uuid, "loteIdLote" uuid, "insumoIdInsumo" uuid, CONSTRAINT "PK_56eaafeca596569647ba5f28334" PRIMARY KEY ("id_alimentacion"))`);
        await queryRunner.query(`CREATE TABLE "insumo" ("id_insumo" uuid NOT NULL DEFAULT uuid_generate_v4(), "id_categoria" uuid NOT NULL, "id_unidad_medida" uuid NOT NULL, "id_llamar_usuario" integer NOT NULL, "nombre" character varying(255) NOT NULL, "cantidad" numeric(10,2) NOT NULL, "fecha" TIMESTAMP NOT NULL, CONSTRAINT "PK_fa3440eab25ef3ba3d737794920" PRIMARY KEY ("id_insumo"))`);
        await queryRunner.query(`CREATE TABLE "llamar_usuario" ("id_llamar_usuario" SERIAL NOT NULL, "id_usuario" uuid NOT NULL, "fecha_creacion" TIMESTAMP NOT NULL DEFAULT now(), "fecha_modificacion" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5d1cb747df5bb70e5bfcc4236ec" PRIMARY KEY ("id_llamar_usuario"))`);
        await queryRunner.query(`CREATE TABLE "permiso" ("id_permiso" SERIAL NOT NULL, "codigo" integer NOT NULL, "descripcion" character varying(255) NOT NULL, CONSTRAINT "PK_80aab004cebf98f1688b787eb7c" PRIMARY KEY ("id_permiso"))`);
        await queryRunner.query(`CREATE TABLE "rol_permiso" ("id_rol_permiso" SERIAL NOT NULL, "id_permiso" integer NOT NULL, "id_rol" integer NOT NULL, CONSTRAINT "PK_151312cfdb886f6d9dc19f9ccfd" PRIMARY KEY ("id_rol_permiso"))`);
        await queryRunner.query(`CREATE TABLE "rol" ("id_rol" SERIAL NOT NULL, "nombre" character varying(255) NOT NULL, CONSTRAINT "PK_0b42a30072d57ccfad9949218da" PRIMARY KEY ("id_rol"))`);
        await queryRunner.query(`CREATE TABLE "usuario_rol" ("id_usuario_rol" SERIAL NOT NULL, "id_usuario" uuid NOT NULL, "id_rol" integer NOT NULL, CONSTRAINT "PK_ca713aaaeccf9816b62b41ebdcb" PRIMARY KEY ("id_usuario_rol"))`);
        await queryRunner.query(`CREATE TABLE "usuario" ("id_usuario" uuid NOT NULL DEFAULT uuid_generate_v4(), "nombre" character varying(255) NOT NULL, "apellido" character varying(255) NOT NULL, "documento" character varying(255) NOT NULL, "fecha_creacion" TIMESTAMP NOT NULL DEFAULT now(), "ultimo_acceso" TIMESTAMP NOT NULL DEFAULT now(), "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "activo" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_2863682842e688ca198eb25c124" UNIQUE ("email"), CONSTRAINT "PK_dd52716c2652e0e23c15530c695" PRIMARY KEY ("id_usuario"))`);
        await queryRunner.query(`CREATE TABLE "reporte" ("id_reporte" uuid NOT NULL DEFAULT uuid_generate_v4(), "tipo_reporte" character varying NOT NULL, "id_usuario" uuid, CONSTRAINT "PK_47bdb6e5b218eb2f5e205dfbbb9" PRIMARY KEY ("id_reporte"))`);
        await queryRunner.query(`CREATE TABLE "finalizacion_lote" ("id_finalizacion_lote" uuid NOT NULL DEFAULT uuid_generate_v4(), "cantidad" integer NOT NULL, "razon" character varying NOT NULL, "fecha" TIMESTAMP NOT NULL DEFAULT now(), "id_lote" uuid, CONSTRAINT "PK_9e88c139f7798bb0c993e174f88" PRIMARY KEY ("id_finalizacion_lote"))`);
        await queryRunner.query(`CREATE TABLE "aves_fallecidas" ("id_aves_fallecidas" uuid NOT NULL DEFAULT uuid_generate_v4(), "cantidad" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "id_lote" uuid, CONSTRAINT "PK_d5001f8bb36323d11a65b802a06" PRIMARY KEY ("id_aves_fallecidas"))`);
        await queryRunner.query(`ALTER TABLE "historial_insumo" ADD CONSTRAINT "FK_91619531ac8d6a8c2b2ae7ae490" FOREIGN KEY ("id_insumos") REFERENCES "insumo"("id_insumo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "historial_insumo" ADD CONSTRAINT "FK_afd9ee94165c7d0181a595d247b" FOREIGN KEY ("id_historial_accion") REFERENCES "accion_historial_movimiento"("id_accion_historial_movimiento") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "historial_asignacion_lote" ADD CONSTRAINT "FK_14818b91ed9cc21835604facbfc" FOREIGN KEY ("id_lote") REFERENCES "lote"("id_lote") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "historial_asignacion_lote" ADD CONSTRAINT "FK_f26a1f4015dee43f03d9bb2f59a" FOREIGN KEY ("id_galpon") REFERENCES "galpon"("id_galpon") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ubicacion_lote" ADD CONSTRAINT "FK_b922245c9ad93aa9907e21be54f" FOREIGN KEY ("id_lote") REFERENCES "lote"("id_lote") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ubicacion_lote" ADD CONSTRAINT "FK_fd5beacc84c40e1b6fe69796329" FOREIGN KEY ("id_galpon") REFERENCES "galpon"("id_galpon") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "estado_lote" ADD CONSTRAINT "FK_d45a6cafbcb5a6dc2b6f5e5cfe7" FOREIGN KEY ("id_lote") REFERENCES "lote"("id_lote") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "huevo_dañado" ADD CONSTRAINT "FK_6103af2db75ab9def3feed9d3e6" FOREIGN KEY ("inventarioIdInventarioHuevo") REFERENCES "inventario_huevo"("id_inventario_huevo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "historial_huevo" ADD CONSTRAINT "FK_fb7ed4b3d577f945a742a6c1565" FOREIGN KEY ("inventarioIdInventarioHuevo") REFERENCES "inventario_huevo"("id_inventario_huevo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "historial_huevo" ADD CONSTRAINT "FK_b7400b3382acadc6a80104f3167" FOREIGN KEY ("produccionIdProduccionHuevo") REFERENCES "produccion_huevo"("id_produccion_huevo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventario_huevo" ADD CONSTRAINT "FK_316c23a916e379efed6e8a42b4b" FOREIGN KEY ("tipo_huevo_id") REFERENCES "tipo_huevo"("id_tipo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventario_huevo" ADD CONSTRAINT "FK_30c41f459b2a6bde0ceabe16397" FOREIGN KEY ("loteIdLote") REFERENCES "lote"("id_lote") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventario_huevo" ADD CONSTRAINT "FK_6db9ce9c62f5b578ceb433ab32a" FOREIGN KEY ("produccionIdProduccionHuevo") REFERENCES "produccion_huevo"("id_produccion_huevo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "produccion_huevo" ADD CONSTRAINT "FK_6248afd2f6ba2993bab2e333c99" FOREIGN KEY ("loteIdLote") REFERENCES "lote"("id_lote") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lote" ADD CONSTRAINT "FK_900ff7ce7db737ba8895fa237be" FOREIGN KEY ("id_raza") REFERENCES "raza"("id_raza") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alimentacion" ADD CONSTRAINT "FK_b5be9914b153a48cf3be3853528" FOREIGN KEY ("usuarioIdUsuario") REFERENCES "usuario"("id_usuario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alimentacion" ADD CONSTRAINT "FK_e9a60b6be65cbe51443b838361e" FOREIGN KEY ("loteIdLote") REFERENCES "lote"("id_lote") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "alimentacion" ADD CONSTRAINT "FK_46b560e4ac93caab22cb430cec1" FOREIGN KEY ("insumoIdInsumo") REFERENCES "insumo"("id_insumo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insumo" ADD CONSTRAINT "FK_4fc30af7b401fb76a04d009a564" FOREIGN KEY ("id_categoria") REFERENCES "categoria_insumo"("id_categoria_insumo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insumo" ADD CONSTRAINT "FK_983c9e0e5709a0ee91eac157a51" FOREIGN KEY ("id_unidad_medida") REFERENCES "unidad_medida"("id_unidad_medida") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "insumo" ADD CONSTRAINT "FK_66761f18f29da02f4f4f6311b3e" FOREIGN KEY ("id_llamar_usuario") REFERENCES "llamar_usuario"("id_llamar_usuario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "llamar_usuario" ADD CONSTRAINT "FK_577eb160128ebafd1f8852d7eb4" FOREIGN KEY ("id_usuario") REFERENCES "usuario"("id_usuario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rol_permiso" ADD CONSTRAINT "FK_9c0fd212b970f71bf0a9465c4f3" FOREIGN KEY ("id_permiso") REFERENCES "permiso"("id_permiso") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rol_permiso" ADD CONSTRAINT "FK_1d9e5be3d74310f98e398912d94" FOREIGN KEY ("id_rol") REFERENCES "rol"("id_rol") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuario_rol" ADD CONSTRAINT "FK_96d2a6ecb2ad0931416610845cf" FOREIGN KEY ("id_rol") REFERENCES "rol"("id_rol") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usuario_rol" ADD CONSTRAINT "FK_6adca3617fc69b2864e67196f2a" FOREIGN KEY ("id_usuario") REFERENCES "usuario"("id_usuario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reporte" ADD CONSTRAINT "FK_27f3ea6a906e5f0702dbe7d3fb2" FOREIGN KEY ("id_usuario") REFERENCES "usuario"("id_usuario") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "finalizacion_lote" ADD CONSTRAINT "FK_ad750c54c18c0fa5fee25bd7b70" FOREIGN KEY ("id_lote") REFERENCES "lote"("id_lote") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "aves_fallecidas" ADD CONSTRAINT "FK_9ddebf439819142049ef223e040" FOREIGN KEY ("id_lote") REFERENCES "lote"("id_lote") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "aves_fallecidas" DROP CONSTRAINT "FK_9ddebf439819142049ef223e040"`);
        await queryRunner.query(`ALTER TABLE "finalizacion_lote" DROP CONSTRAINT "FK_ad750c54c18c0fa5fee25bd7b70"`);
        await queryRunner.query(`ALTER TABLE "reporte" DROP CONSTRAINT "FK_27f3ea6a906e5f0702dbe7d3fb2"`);
        await queryRunner.query(`ALTER TABLE "usuario_rol" DROP CONSTRAINT "FK_6adca3617fc69b2864e67196f2a"`);
        await queryRunner.query(`ALTER TABLE "usuario_rol" DROP CONSTRAINT "FK_96d2a6ecb2ad0931416610845cf"`);
        await queryRunner.query(`ALTER TABLE "rol_permiso" DROP CONSTRAINT "FK_1d9e5be3d74310f98e398912d94"`);
        await queryRunner.query(`ALTER TABLE "rol_permiso" DROP CONSTRAINT "FK_9c0fd212b970f71bf0a9465c4f3"`);
        await queryRunner.query(`ALTER TABLE "llamar_usuario" DROP CONSTRAINT "FK_577eb160128ebafd1f8852d7eb4"`);
        await queryRunner.query(`ALTER TABLE "insumo" DROP CONSTRAINT "FK_66761f18f29da02f4f4f6311b3e"`);
        await queryRunner.query(`ALTER TABLE "insumo" DROP CONSTRAINT "FK_983c9e0e5709a0ee91eac157a51"`);
        await queryRunner.query(`ALTER TABLE "insumo" DROP CONSTRAINT "FK_4fc30af7b401fb76a04d009a564"`);
        await queryRunner.query(`ALTER TABLE "alimentacion" DROP CONSTRAINT "FK_46b560e4ac93caab22cb430cec1"`);
        await queryRunner.query(`ALTER TABLE "alimentacion" DROP CONSTRAINT "FK_e9a60b6be65cbe51443b838361e"`);
        await queryRunner.query(`ALTER TABLE "alimentacion" DROP CONSTRAINT "FK_b5be9914b153a48cf3be3853528"`);
        await queryRunner.query(`ALTER TABLE "lote" DROP CONSTRAINT "FK_900ff7ce7db737ba8895fa237be"`);
        await queryRunner.query(`ALTER TABLE "produccion_huevo" DROP CONSTRAINT "FK_6248afd2f6ba2993bab2e333c99"`);
        await queryRunner.query(`ALTER TABLE "inventario_huevo" DROP CONSTRAINT "FK_6db9ce9c62f5b578ceb433ab32a"`);
        await queryRunner.query(`ALTER TABLE "inventario_huevo" DROP CONSTRAINT "FK_30c41f459b2a6bde0ceabe16397"`);
        await queryRunner.query(`ALTER TABLE "inventario_huevo" DROP CONSTRAINT "FK_316c23a916e379efed6e8a42b4b"`);
        await queryRunner.query(`ALTER TABLE "historial_huevo" DROP CONSTRAINT "FK_b7400b3382acadc6a80104f3167"`);
        await queryRunner.query(`ALTER TABLE "historial_huevo" DROP CONSTRAINT "FK_fb7ed4b3d577f945a742a6c1565"`);
        await queryRunner.query(`ALTER TABLE "huevo_dañado" DROP CONSTRAINT "FK_6103af2db75ab9def3feed9d3e6"`);
        await queryRunner.query(`ALTER TABLE "estado_lote" DROP CONSTRAINT "FK_d45a6cafbcb5a6dc2b6f5e5cfe7"`);
        await queryRunner.query(`ALTER TABLE "ubicacion_lote" DROP CONSTRAINT "FK_fd5beacc84c40e1b6fe69796329"`);
        await queryRunner.query(`ALTER TABLE "ubicacion_lote" DROP CONSTRAINT "FK_b922245c9ad93aa9907e21be54f"`);
        await queryRunner.query(`ALTER TABLE "historial_asignacion_lote" DROP CONSTRAINT "FK_f26a1f4015dee43f03d9bb2f59a"`);
        await queryRunner.query(`ALTER TABLE "historial_asignacion_lote" DROP CONSTRAINT "FK_14818b91ed9cc21835604facbfc"`);
        await queryRunner.query(`ALTER TABLE "historial_insumo" DROP CONSTRAINT "FK_afd9ee94165c7d0181a595d247b"`);
        await queryRunner.query(`ALTER TABLE "historial_insumo" DROP CONSTRAINT "FK_91619531ac8d6a8c2b2ae7ae490"`);
        await queryRunner.query(`DROP TABLE "aves_fallecidas"`);
        await queryRunner.query(`DROP TABLE "finalizacion_lote"`);
        await queryRunner.query(`DROP TABLE "reporte"`);
        await queryRunner.query(`DROP TABLE "usuario"`);
        await queryRunner.query(`DROP TABLE "usuario_rol"`);
        await queryRunner.query(`DROP TABLE "rol"`);
        await queryRunner.query(`DROP TABLE "rol_permiso"`);
        await queryRunner.query(`DROP TABLE "permiso"`);
        await queryRunner.query(`DROP TABLE "llamar_usuario"`);
        await queryRunner.query(`DROP TABLE "insumo"`);
        await queryRunner.query(`DROP TABLE "alimentacion"`);
        await queryRunner.query(`DROP TABLE "lote"`);
        await queryRunner.query(`DROP TABLE "produccion_huevo"`);
        await queryRunner.query(`DROP TABLE "inventario_huevo"`);
        await queryRunner.query(`DROP TABLE "tipo_huevo"`);
        await queryRunner.query(`DROP TABLE "historial_huevo"`);
        await queryRunner.query(`DROP TABLE "huevo_dañado"`);
        await queryRunner.query(`DROP TABLE "estado_lote"`);
        await queryRunner.query(`DROP TABLE "ubicacion_lote"`);
        await queryRunner.query(`DROP TABLE "galpon"`);
        await queryRunner.query(`DROP TABLE "historial_asignacion_lote"`);
        await queryRunner.query(`DROP TABLE "raza"`);
        await queryRunner.query(`DROP TABLE "historial_insumo"`);
        await queryRunner.query(`DROP TABLE "accion_historial_movimiento"`);
        await queryRunner.query(`DROP TABLE "unidad_medida"`);
        await queryRunner.query(`DROP TABLE "categoria_insumo"`);
    }
}
